### ISSUE TITLE
Linux ARM 64 support

### ISSUE THREAD

**Issue by blackrez** [ankane/cmdstan-ruby#3]
Hello,

The installation of rb-prophet fails on linux arm64. 

I think this is due to the usage of stanc for amd64 processors.
```
Building native extensions. This could take a while...
ERROR:  Error installing prophet-rb:
	ERROR: Failed to build gem native extension.

    current directory: /home/nabil/.rvm/gems/ruby-3.1.0/gems/prophet-rb-0.2.5/ext/prophet
/home/nabil/.rvm/rubies/ruby-3.1.0/bin/ruby -I /home/nabil/.rvm/rubies/ruby-3.1.0/lib/ruby/3.1.0 -r ./siteconf20220207-43224-e9mn2a.rb extconf.rb
g++ -std=c++1y -pthread -D_REENTRANT -Wno-sign-compare -Wno-ignored-attributes      -I stan/lib/stan_math/lib/tbb_2020.3/include    -O3 -I src -I stan/src -I lib/rapidjson_1.1.0/ -I lib/CLI11-1.9.1/ -I stan/lib/stan_math/ -I stan/lib/stan_math/lib/eigen_3.3.9 -I stan/lib/stan_math/lib/boost_1.75.0 -I stan/lib/stan_math/lib/sundials_5.7.0/include    -DBOOST_DISABLE_ASSERTS          -c -MT stan/src/stan/model/model_header.hpp.gch -MT stan/src/stan/model/model_header.d -MM -E -MG -MP -MF stan/src/stan/model/model_header.d stan/src/stan/model/model_header.hpp
g++ -std=c++1y -pthread -D_REENTRANT -Wno-sign-compare -Wno-ignored-attributes      -I stan/lib/stan_math/lib/tbb_2020.3/include    -O3 -I src -I stan/src -I lib/rapidjson_1.1.0/ -I lib/CLI11-1.9.1/ -I stan/lib/stan_math/ -I stan/lib/stan_math/lib/eigen_3.3.9 -I stan/lib/stan_math/lib/boost_1.75.0 -I stan/lib/stan_math/lib/sundials_5.7.0/include    -DBOOST_DISABLE_ASSERTS          -c -MT src/cmdstan/main.o -MM -E -MG -MP -MF src/cmdstan/main.d src/cmdstan/main.cpp

--- Translating Stan model to C++ code ---
bin/stanc  --o=/tmp/prophet.hpp /tmp/prophet.stan
bash: bin/stanc: cannot execute binary file: Exec format error
make: *** [make/program:50: /tmp/prophet.hpp] Error 126
/home/nabil/.rvm/gems/ruby-3.1.0/gems/cmdstan-0.1.8/lib/cmdstan/utils.rb:24:in `run_command': Command failed (CmdStan::Error)
	from /home/nabil/.rvm/gems/ruby-3.1.0/gems/cmdstan-0.1.8/lib/cmdstan/model.rb:22:in `block in compile'
	from /home/nabil/.rvm/gems/ruby-3.1.0/gems/cmdstan-0.1.8/lib/cmdstan/model.rb:21:in `chdir'
	from /home/nabil/.rvm/gems/ruby-3.1.0/gems/cmdstan-0.1.8/lib/cmdstan/model.rb:21:in `compile'
	from /home/nabil/.rvm/gems/ruby-3.1.0/gems/cmdstan-0.1.8/lib/cmdstan/model.rb:16:in `initialize'
	from extconf.rb:13:in `new'
	from extconf.rb:13:in `<main>'

extconf failed, exit code 1
```

Binaries for cmdstan are available for linux-arm64, what is the best way to support arm64 ?

Thanks.

**Comment by ankane** [comment]
Fixed in #4
